parser: "@typescript-eslint/parser"
extends:
  - eslint-config-blvd/react
  - plugin:prettier/recommended
  - plugin:import/typescript
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
rules:
  import/prefer-default-export: off
  "@typescript-eslint/explicit-function-return-type": off
  react/no-unescaped-entities:
    - error
    -
      forbid:
        - char: ">"
          alternatives:
            - "&gt;"
        - char: "}"
          alternatives:
            - "&#125;"
  "@typescript-eslint/no-empty-function": off
  no-nested-ternary: off
  react/jsx-props-no-spreading: off
  react/no-danger: off
  camelcase: off
