parser: '@typescript-eslint/parser'
plugins:
  - prettier
extends:
  - plugin:import/typescript
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
rules:
  prettier/prettier: 'error'
  import/prefer-default-export: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-empty-function': off
  no-nested-ternary: off
  react/jsx-props-no-spreading: off
  react/no-danger: off
  camelcase: off
