nodeLinker: node-modules

packageExtensions:
  commitlint-config-gitmoji@*:
    dependencies:
      "@commitlint/types": ^17.0.0
  eslint-config-next@*:
    dependencies:
      next: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
