nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  'commitlint-config-gitmoji@*':
    dependencies:
      '@commitlint/types': '^17.0.0'
