nodeLinker: pnp
pnpMode: 'loose'
pnpFallbackMode: 'all'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: '>= 2.7'
      webpack: '>= 4'
  babel-preset-gatsby-package@0.1.4:
    peerDependencies:
      '@babel/core': '^7.0.0-0'
  gatsby@4.3.0:
    peerDependencies:
      babel-eslint: '^7.0.0-0'
      typescript: '>= 2.7'
  react-spring@9.3.2:
    peerDependencies:
      '@react-three/fiber': '>=6.0'
      konva: '>=2.6'
      react: '*'
      react-dom: '*'
      react-konva: '*'
      react-native: '*'
      react-zdog: '*'
      three: '>=0.126'
      zdog: '*'
    peerDependenciesMeta:
      '@react-three/fiber':
        optional: true
      konva:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      react-konva:
        optional: true
      react-native:
        optional: true
      react-zdog:
        optional: true
      three:
        optional: true
      zdog:
        optional: true
