nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  react-spring@9.3.2:
    peerDependencies:
      '@react-three/fiber': '>=6.0'
      konva: '>=2.6'
      react: '*'
      react-dom: '*'
      react-konva: '*'
      react-native: '*'
      react-zdog: '*'
      three: '>=0.126'
      zdog: '*'
    peerDependenciesMeta:
      '@react-three/fiber':
        optional: true
      konva:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      react-konva:
        optional: true
      react-native:
        optional: true
      react-zdog:
        optional: true
      three:
        optional: true
      zdog:
        optional: true
